/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica_dental;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import cjb.ci.Mensaje;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import pckBakcend.Consulta;

/**
 *
 * @author chemo
 */
public class VtnAgendar_Cita extends javax.swing.JFrame
{
    private int posicion;
    public VtnAgendar_Cita()
    {
        initComponents();
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apellidoPaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        motivo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        diaCita = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        mesCita = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        horaCita = new javax.swing.JComboBox<>();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Aceptar1 = new javax.swing.JCheckBox();
        Aceptar2 = new javax.swing.JCheckBox();
        Salir = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cve = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        anio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clinica Dental Prestige");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("Clínica Dental");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 19, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("P R E S T I G E");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 56, 186, -1));

        jPanel3.setBackground(new java.awt.Color(204, 102, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 1000, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        nombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreKeyTyped(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Apellido Paterno:");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        apellidoPaterno.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        apellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                apellidoPaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apellidoPaternoKeyTyped(evt);
            }
        });
        jPanel1.add(apellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Dia:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Mes:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Año:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setText("Datos personales");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 710, 10));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Numero de Contacto:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        numero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        numero.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                numeroKeyTyped(evt);
            }
        });
        jPanel1.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 260, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Correo Electronico:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        correo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        correo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                correoKeyTyped(evt);
            }
        });
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 220, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setText("Programación de Cita");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Motivo de Cita:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        motivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        motivo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                motivoKeyTyped(evt);
            }
        });
        jPanel1.add(motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 220, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Fecha y Hora Preferida:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 170, -1));

        diaCita.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        diaCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(diaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Dia:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Mes:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        mesCita.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mesCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel1.add(mesCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 80, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Hora:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        horaCita.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        horaCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00 a.m.", "9:30 a.m.", "10:00 a.m.", "10:30 a.m.", "11:00 a.m.", "11:30 a.m.", "12:00 p.m.", "12:30 p.m.", "1:00 p.m.", "1:30 p.m.", "2:00 p.m.", "2:30 p.m.", "3:00 p.m.", "3:30 p.m.", "4:00 p.m.", "4:30 p.m." }));
        jPanel1.add(horaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 80, -1));

        Aceptar.setBackground(new java.awt.Color(153, 153, 255));
        Aceptar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("ACEPTAR");
        Aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 260, 30));

        Cancelar.setBackground(new java.awt.Color(255, 102, 102));
        Cancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("CANCELAR");
        Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 260, 30));

        Aceptar1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Aceptar1.setText("Acepto recibir tratamiento dental.");
        jPanel1.add(Aceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        Aceptar2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Aceptar2.setText("Acepto el manejo de mis datos personales según las leyes de privacidad.");
        jPanel1.add(Aceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        Salir.setBackground(new java.awt.Color(102, 102, 255));
        Salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 10, 140, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setText("Ingrese su CVE:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 110, -1));

        cve.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cve.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cveActionPerformed(evt);
            }
        });
        jPanel1.add(cve, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 100, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 100, -1));

        dia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diaActionPerformed(evt);
            }
        });
        jPanel1.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 60, -1));
        jPanel1.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 80, -1));
        jPanel1.add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 80, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Edad:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        edad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        edad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                edadActionPerformed(evt);
            }
        });
        jPanel1.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 260, -1));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR CITA");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 140, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 600));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AceptarActionPerformed
    {//GEN-HEADEREND:event_AceptarActionPerformed
        try
        {
            if (Aceptar1.isSelected() && Aceptar2.isSelected())
            {
                String numReferencia = pckBakcend.PrbClinicaDental.generarReferenciaPago();

                String diaStr = this.diaCita.getSelectedItem().toString();
                int diaC = Integer.parseInt(diaStr);

                String mesC = this.mesCita.getSelectedItem().toString();

                String hora = this.horaCita.getSelectedItem().toString();

                int edadIngresada = Integer.parseInt(edad.getText());

                Consulta nuevaConsulta = new Consulta(nombre.getText(), apellidoPaterno.getText(), edadIngresada, numero.getText(), correo.getText(), motivo.getText(), diaC, mesC, hora, false, numReferencia, false);
                VtnIncio_Secion.consulta = pckBakcend.PrbClinicaDental.insertaConsulta(VtnIncio_Secion.consulta, nuevaConsulta, posicion);
                Mensaje.exito(this, "Consulta Registrada Con Exito\nNumero de Referencia: " + numReferencia);
                
                archivos.Archivos.guardaArr(this, VtnIncio_Secion.consulta, "DatosMatriz.dat");

                System.out.println(nuevaConsulta);
                
                CtrlInterfaz.limpia(nombre,apellidoPaterno, correo, dia, mes, anio, numero, edad, motivo,diaCita, mesCita, horaCita);
            } else
            {
                Mensaje.error(this, "Acepte los acuerdos de privacidad");
            }
        } catch (Exception e)
        {
            System.out.println("Error..." + e.toString());
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SalirActionPerformed
    {//GEN-HEADEREND:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarActionPerformed
    {//GEN-HEADEREND:event_CancelarActionPerformed
        CtrlInterfaz.limpia(nombre, apellidoPaterno, numero, correo, dia, mes, anio, diaCita, mesCita, horaCita, motivo, Aceptar1, Aceptar2);
    }//GEN-LAST:event_CancelarActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreKeyTyped
    {//GEN-HEADEREND:event_nombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_nombreKeyTyped

    private void apellidoPaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoPaternoKeyTyped
    {//GEN-HEADEREND:event_apellidoPaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_apellidoPaternoKeyTyped

    private void motivoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_motivoKeyTyped
    {//GEN-HEADEREND:event_motivoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_motivoKeyTyped

    private void nombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreKeyPressed
    {//GEN-HEADEREND:event_nombreKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nombre, apellidoPaterno);
    }//GEN-LAST:event_nombreKeyPressed

    private void apellidoPaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoPaternoKeyPressed
    {//GEN-HEADEREND:event_apellidoPaternoKeyPressed

    }//GEN-LAST:event_apellidoPaternoKeyPressed

    private void numeroKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numeroKeyTyped
    {//GEN-HEADEREND:event_numeroKeyTyped
        Validaciones.enterCadenaNoVacia(this, evt, numero, correo);
    }//GEN-LAST:event_numeroKeyTyped

    private void correoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_correoKeyTyped
    {//GEN-HEADEREND:event_correoKeyTyped
        Validaciones.enterCadenaNoVacia(this, evt, correo, motivo);
    }//GEN-LAST:event_correoKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        CtrlInterfaz.habilita(false, nombre, apellidoPaterno, numero, correo, dia, mes, anio, motivo, diaCita, mesCita, horaCita, Aceptar, edad);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        try
        {
            int cveIngresado = Integer.parseInt(this.cve.getText());
            int posUsuario = pckBakcend.PrbClinicaDental.buscarPosCVE(VtnIncio_Secion.usuario, cveIngresado);
            posicion = posUsuario;
            if (posUsuario != -1)
            {
                CtrlInterfaz.habilita(true, nombre, apellidoPaterno, numero, correo, dia, mes, anio, motivo, diaCita, mesCita, horaCita, Aceptar, edad);
                nombre.setText(VtnIncio_Secion.usuario[posUsuario].getNombre());
                apellidoPaterno.setText(VtnIncio_Secion.usuario[posUsuario].getApellido());
                correo.setText(VtnIncio_Secion.usuario[posUsuario].getCorreo());
                dia.setText(String.valueOf(VtnIncio_Secion.usuario[posUsuario].getDia()));
                mes.setText(VtnIncio_Secion.usuario[posUsuario].getMes());
                anio.setText(String.valueOf(VtnIncio_Secion.usuario[posUsuario].getAnio()));   
            } else
            {
                Mensaje.error(this, "CVE No Encontrado");
                CtrlInterfaz.limpia(cve);
            }
        } catch (Exception e)
        {
            System.out.println("Error..." + e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diaActionPerformed
    {//GEN-HEADEREND:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_edadActionPerformed
    {//GEN-HEADEREND:event_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadActionPerformed

    private void cveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cveActionPerformed
    {//GEN-HEADEREND:event_cveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        new VtnCancelarCita().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex)
        {
            java.util.logging.Logger.getLogger(VtnAgendar_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                int posicion = 0; // Valor predeterminado
                new VtnAgendar_Cita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JCheckBox Aceptar1;
    private javax.swing.JCheckBox Aceptar2;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField anio;
    private javax.swing.JTextField apellidoPaterno;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField cve;
    private javax.swing.JTextField dia;
    private javax.swing.JComboBox<String> diaCita;
    private javax.swing.JTextField edad;
    private javax.swing.JComboBox<String> horaCita;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mes;
    private javax.swing.JComboBox<String> mesCita;
    private javax.swing.JTextField motivo;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables
}
