/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica_dental;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import cjb.ci.Mensaje;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author chemo
 */
public class VtnAgendar_Cita extends javax.swing.JFrame
{
    public VtnAgendar_Cita()
    {
        initComponents();
        setIconImage(getIconImage());
    }
    
    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        APaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AMaterno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Dia_1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Mes_1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Año_1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        Numero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Motivo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Dia_2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Mes_2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        Hora_1 = new javax.swing.JComboBox<>();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Aceptar1 = new javax.swing.JCheckBox();
        Aceptar2 = new javax.swing.JCheckBox();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clinica Dental Prestige");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("Clínica Dental");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 19, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("P R E S T I G E");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 56, 186, -1));

        jPanel3.setBackground(new java.awt.Color(204, 102, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 1000, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        Nombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Nombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                NombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                NombreKeyTyped(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Apellido Paterno:");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        APaterno.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        APaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                APaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                APaternoKeyTyped(evt);
            }
        });
        jPanel1.add(APaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Apellido Materno:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        AMaterno.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        AMaterno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                AMaternoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                AMaternoKeyTyped(evt);
            }
        });
        jPanel1.add(AMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 220, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        Dia_1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Dia_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        jPanel1.add(Dia_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Dia:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Mes:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        Mes_1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Mes_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        jPanel1.add(Mes_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 80, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Año:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        Año_1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Año_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", " " }));
        jPanel1.add(Año_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setText("Datos personales");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 710, 10));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Numero de Contacto:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        Numero.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Numero.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                NumeroKeyTyped(evt);
            }
        });
        jPanel1.add(Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 260, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Correo Electronico:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        Correo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Correo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CorreoKeyTyped(evt);
            }
        });
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 260, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel14.setText("Programación de Cita");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Motivo de Cita:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        Motivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Motivo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                MotivoKeyTyped(evt);
            }
        });
        jPanel1.add(Motivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 220, 30));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Fecha y Hora Preferida:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 170, -1));

        Dia_2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Dia_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        jPanel1.add(Dia_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Dia:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Mes:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        Mes_2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Mes_2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        jPanel1.add(Mes_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 80, -1));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Hora:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, -1));

        Hora_1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Hora_1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00 a.m.", "9:30 a.m.", "10:00 a.m.", "10:30 a.m.", "11:00 a.m.", "11:30 a.m.", "12:00 p.m.", "12:30 p.m.", "1:00 p.m.", "1:30 p.m.", "2:00 p.m.", "2:30 p.m.", "3:00 p.m.", "3:30 p.m.", "4:00 p.m.", "4:30 p.m.", " " }));
        jPanel1.add(Hora_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 80, -1));

        Aceptar.setBackground(new java.awt.Color(153, 153, 255));
        Aceptar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Aceptar.setText("ACEPTAR");
        Aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 260, 30));

        Cancelar.setBackground(new java.awt.Color(255, 102, 102));
        Cancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("CANCELAR");
        Cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 260, 30));

        Aceptar1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Aceptar1.setText("Acepto recibir tratamiento dental.");
        jPanel1.add(Aceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        Aceptar2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Aceptar2.setText("Acepto el manejo de mis datos personales según las leyes de privacidad.");
        jPanel1.add(Aceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        Salir.setBackground(new java.awt.Color(102, 102, 255));
        Salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 10, 110, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 600));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AceptarActionPerformed
    {//GEN-HEADEREND:event_AceptarActionPerformed
        String emailIngresado = Correo.getText();
        String NumeroInput = Numero.getText();
        String emailPattern = "^[a-zA-Z0-9._%+-]+@(gmail|hotmail|outlook|yahoo)\\.[a-zA-Z]{2,}$";
        String NumeroPattern = "^[0-9]{10}$";

        Pattern emailPat = Pattern.compile(emailPattern);
        Matcher emailMatcher = emailPat.matcher(emailIngresado);
        
        Pattern NumeroPat = Pattern.compile(NumeroPattern);
        Matcher NumeroMatcher = NumeroPat.matcher(NumeroInput);

        boolean isValidEmail = emailMatcher.matches();
         boolean isValidNnumero = NumeroMatcher.matches();
        
        if (isValidEmail && isValidNnumero)
        {
            if (Aceptar1.isSelected() && Aceptar2.isSelected())
            {
                Mensaje.exito(this, "Cita agendada con exito"); 
            }
            else
            {
                Mensaje.error(this, "Acepte los acuerdos de privacidad");
            }
        }
        else
        {
            Mensaje.error(this, "Correo electrónico y/o número de celular inválido");
            CtrlInterfaz.limpia(Correo,Numero);
        }
        
        /*if (Aceptar1.isSelected() && Aceptar2.isSelected())
        {
            Mensaje.exito(this, "Cita agendada con exito");
        }
        else
        {
            Mensaje.error(this, "Acepte los acuerdos de privacidad");
        }*/
    }//GEN-LAST:event_AceptarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SalirActionPerformed
    {//GEN-HEADEREND:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarActionPerformed
    {//GEN-HEADEREND:event_CancelarActionPerformed
        CtrlInterfaz.limpia(Nombre,APaterno,AMaterno, Numero, Correo, Dia_1, Mes_1, Año_1, Dia_2, Mes_2, Hora_1, Motivo, Aceptar1, Aceptar2);
    }//GEN-LAST:event_CancelarActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NombreKeyTyped
    {//GEN-HEADEREND:event_NombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_NombreKeyTyped

    private void APaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_APaternoKeyTyped
    {//GEN-HEADEREND:event_APaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_APaternoKeyTyped

    private void AMaternoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_AMaternoKeyTyped
    {//GEN-HEADEREND:event_AMaternoKeyTyped
        Validaciones.validaAlfabeticos(evt);
        Validaciones.enterCadenaNoVacia(this, evt, Motivo, Aceptar);
    }//GEN-LAST:event_AMaternoKeyTyped

    private void MotivoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_MotivoKeyTyped
    {//GEN-HEADEREND:event_MotivoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_MotivoKeyTyped

    private void NombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NombreKeyPressed
    {//GEN-HEADEREND:event_NombreKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, Nombre, APaterno);
    }//GEN-LAST:event_NombreKeyPressed

    private void APaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_APaternoKeyPressed
    {//GEN-HEADEREND:event_APaternoKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, APaterno, AMaterno);
    }//GEN-LAST:event_APaternoKeyPressed

    private void AMaternoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_AMaternoKeyPressed
    {//GEN-HEADEREND:event_AMaternoKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, AMaterno, Numero);
    }//GEN-LAST:event_AMaternoKeyPressed

    private void NumeroKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_NumeroKeyTyped
    {//GEN-HEADEREND:event_NumeroKeyTyped
        Validaciones.enterCadenaNoVacia(this, evt, Numero, Correo);
    }//GEN-LAST:event_NumeroKeyTyped

    private void CorreoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CorreoKeyTyped
    {//GEN-HEADEREND:event_CorreoKeyTyped
        Validaciones.enterCadenaNoVacia(this, evt, Correo, Motivo);
    }//GEN-LAST:event_CorreoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnAgendar_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnAgendar_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnAgendar_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnAgendar_Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnAgendar_Cita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AMaterno;
    private javax.swing.JTextField APaterno;
    private javax.swing.JButton Aceptar;
    private javax.swing.JCheckBox Aceptar1;
    private javax.swing.JCheckBox Aceptar2;
    private javax.swing.JComboBox<String> Año_1;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField Correo;
    private javax.swing.JComboBox<String> Dia_1;
    private javax.swing.JComboBox<String> Dia_2;
    private javax.swing.JComboBox<String> Hora_1;
    private javax.swing.JComboBox<String> Mes_1;
    private javax.swing.JComboBox<String> Mes_2;
    private javax.swing.JTextField Motivo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Numero;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
