/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica_dental;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import cjb.ci.Mensaje;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import pckBakcend.PagoRealizado;

/**
 *
 * @author chemo
 */
public class VtnMetodo_de_pago extends javax.swing.JFrame
{

    public VtnMetodo_de_pago()
    {
        initComponents();
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Salir = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        referencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tarjeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mes = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        anio = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cvv = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Aceptar_1 = new javax.swing.JCheckBox();
        Aceptar_2 = new javax.swing.JCheckBox();
        pago = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clinica Dental Prestige");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 100, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("Clínica Dental");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 19, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("P R E S T I G E");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 56, 186, -1));

        jPanel3.setBackground(new java.awt.Color(204, 102, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 5));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 1000, -1));

        Salir.setBackground(new java.awt.Color(102, 102, 255));
        Salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 110, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel20.setText("Información de facturación");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Nombre del titular:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        referencia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        referencia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                referenciaActionPerformed(evt);
            }
        });
        referencia.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                referenciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                referenciaKeyTyped(evt);
            }
        });
        jPanel1.add(referencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 300, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Numero de tarjeta:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        tarjeta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tarjeta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 300, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/visa.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 50, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Master card.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/amex.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/paypal.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 40, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/american-express.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 40, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Fecha de expiración:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Mes:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        mes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel1.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 70, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Año:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jPanel1.add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("CVV:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cvv.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, 30));

        cvv.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cvv.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cvvActionPerformed(evt);
            }
        });
        cvv.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cvvKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                cvvKeyTyped(evt);
            }
        });
        jPanel1.add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 100, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel16.setText("Se encuentra el reverso de su tarjeta");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 200, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/openpay-color.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel17.setText("Transacciones realizadas via:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 20, 80));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Escudo.png"))); // NOI18N
        jLabel19.setText(" Tus pagos se realizan de forma segura");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, 50));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel21.setText("con encriptación de 252 bits");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        Aceptar_1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Aceptar_1.setText("Acepto aviso de privacidad");
        jPanel1.add(Aceptar_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        Aceptar_2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Aceptar_2.setText("Acepto términos y ccondiciones");
        jPanel1.add(Aceptar_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        pago.setBackground(new java.awt.Color(153, 153, 255));
        pago.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pago.setForeground(new java.awt.Color(255, 255, 255));
        pago.setText("Realizar Pago");
        pago.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pagoActionPerformed(evt);
            }
        });
        jPanel1.add(pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 140, 30));

        cancelar.setBackground(new java.awt.Color(255, 102, 153));
        cancelar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 140, 30));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Numero de Referencia:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        nombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombreActionPerformed(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 300, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 600));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SalirActionPerformed
    {//GEN-HEADEREND:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void referenciaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_referenciaActionPerformed
    {//GEN-HEADEREND:event_referenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenciaActionPerformed

    private void cvvActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cvvActionPerformed
    {//GEN-HEADEREND:event_cvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvActionPerformed

    private void pagoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pagoActionPerformed
    {//GEN-HEADEREND:event_pagoActionPerformed
        try
        {
            String tarjetaIngresada = tarjeta.getText();
            String tarjetaPattern = "^[0-9]{16}$";

            String cvvIngresada = cvv.getText();
            String cvvPattern = "^[0-9]{3}$";

            Pattern tarjetaPat = Pattern.compile(tarjetaPattern);
            Matcher tarjetaMatcher = tarjetaPat.matcher(tarjetaIngresada);

            Pattern cvvPat = Pattern.compile(cvvPattern);
            Matcher cvvMatcher = cvvPat.matcher(cvvIngresada);

            boolean isValidTarjeta = tarjetaMatcher.matches();
            boolean isValidcvv = cvvMatcher.matches();

            String numReferencia = referencia.getText();
            String nombreTitular = nombre.getText();
            String tarjeta = tarjetaIngresada;
            String mesSeleccionado = (String) mes.getSelectedItem();
            String anioSeleccionadoString = (String) anio.getSelectedItem();
            int anioSeleccionado = Integer.parseInt(anioSeleccionadoString); // Conversión de String a int
            int cvvIngresado = Integer.parseInt(cvv.getText());
            Date fechaActual = obtenerFechaActual();

            if (VtnIncio_Secion.consulta != null)
            {
                for (int i = 0; i < VtnIncio_Secion.consulta.length; i++)
                {
                    if (VtnIncio_Secion.consulta[i] != null)
                    { // Verifica que consulta[i] no sea null
                        for (int j = 0; j < VtnIncio_Secion.consulta[i].length; j++)
                        {
                            if (VtnIncio_Secion.consulta[i][j] != null
                                    && VtnIncio_Secion.consulta[i][j].getNumeroDeReferencia().equals(numReferencia))
                            {

                                if (isValidTarjeta && isValidcvv)
                                {
                                    if (Aceptar_1.isSelected() && Aceptar_2.isSelected())
                                    {
                                        PagoRealizado nuevoPago = new PagoRealizado(numReferencia, fechaActual, nombreTitular, tarjeta, mesSeleccionado, anioSeleccionado, cvvIngresado);
                                        VtnIncio_Secion.consulta[i][j].setEstatusPago(true);
                                        Mensaje.exito(this, "Pago Realizado Con Exito");
                                        System.out.println(nuevoPago);
                                        VtnIncio_Secion.pagoRealizado = pckBakcend.PrbClinicaDental.insertaPagos(VtnIncio_Secion.pagoRealizado, nuevoPago, i);
                                        archivos.Archivos.guardaArr(this, VtnIncio_Secion.pagoRealizado, "DatosPagos.dat");
                                        archivos.Archivos.guardaArr(this, VtnIncio_Secion.consulta, "DatosMatriz.dat");
                                    } else
                                    {
                                        Mensaje.error(this, "Acepte los derechos de privacidad");
                                    }
                                } else
                                {
                                    Mensaje.error(this, "Numero de tarjeta y/o CVV invalido");
                                    CtrlInterfaz.limpia(this.tarjeta, cvv);
                                }
                            }
                        }
                    }
                }
            } else
            {
                Mensaje.error(this, "El Usuario No Tiene Consultas Registradas");
                CtrlInterfaz.limpia(referencia, nombre, this.tarjeta, mes, anio, cvv);
                Aceptar_1.setSelected(false);
                Aceptar_2.setSelected(false);
            }
        } catch (Exception e)
        {
            System.out.println("Error..." + e.toString());
        }
    }//GEN-LAST:event_pagoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarActionPerformed
    {//GEN-HEADEREND:event_cancelarActionPerformed
        CtrlInterfaz.limpia(referencia, tarjeta, mes, anio, Aceptar_1, Aceptar_2, cvv);
    }//GEN-LAST:event_cancelarActionPerformed

    private void referenciaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_referenciaKeyTyped
    {//GEN-HEADEREND:event_referenciaKeyTyped

    }//GEN-LAST:event_referenciaKeyTyped

    private void tarjetaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tarjetaActionPerformed
    {//GEN-HEADEREND:event_tarjetaActionPerformed

    }//GEN-LAST:event_tarjetaActionPerformed

    private void referenciaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_referenciaKeyPressed
    {//GEN-HEADEREND:event_referenciaKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, referencia, tarjeta);
    }//GEN-LAST:event_referenciaKeyPressed

    private void cvvKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cvvKeyPressed
    {//GEN-HEADEREND:event_cvvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvKeyPressed

    private void cvvKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cvvKeyTyped
    {//GEN-HEADEREND:event_cvvKeyTyped

    }//GEN-LAST:event_cvvKeyTyped

    private void nombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombreActionPerformed
    {//GEN-HEADEREND:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    public static Date obtenerFechaActual()
    {
        return new Date(); // Devuelve la fecha actual
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnMetodo_de_pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnMetodo_de_pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnMetodo_de_pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnMetodo_de_pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnMetodo_de_pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Aceptar_1;
    private javax.swing.JCheckBox Aceptar_2;
    private javax.swing.JButton Salir;
    private javax.swing.JComboBox<String> anio;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cvv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> mes;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton pago;
    private javax.swing.JTextField referencia;
    private javax.swing.JTextField tarjeta;
    // End of variables declaration//GEN-END:variables
}
