/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinica_dental;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Validaciones;
import cjb.ci.Mensaje;
import static clinica_dental.VtnIncio_Secion.consulta;
import static clinica_dental.VtnIncio_Secion.metodoPago;
import static clinica_dental.VtnIncio_Secion.pagoRealizado;
import static clinica_dental.VtnIncio_Secion.usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.ObjectInputStream;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static pckBakcend.PrbClinicaDental.crearMatrizConsulta;
import static pckBakcend.PrbClinicaDental.crearMatrizMetodoDePago;
import static pckBakcend.PrbClinicaDental.crearMatrizPagos;
import static pckBakcend.PrbClinicaDental.insertaUsuario;
import pckBakcend.Usuario;

/**
 *
 * @author chemo
 */
public class VtnRegistro extends javax.swing.JFrame
{

    /**
     * Creates new form VtnIncio_Secion
     */
    public VtnRegistro()
    {
        initComponents();
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        aceptar = new javax.swing.JToggleButton();
        apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Mes = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        anio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Contra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clinica Dental Prestige");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mes.setBackground(new java.awt.Color(255, 255, 255));
        mes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil-del-usuario.png"))); // NOI18N
        mes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Crear nueva cuenta");
        mes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Nombre");
        mes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        nombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nombre.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombreKeyTyped(evt);
            }
        });
        mes.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 280, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Apellido");
        mes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        aceptar.setBackground(new java.awt.Color(102, 102, 255));
        aceptar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarActionPerformed(evt);
            }
        });
        mes.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 280, 40));

        apellido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        apellido.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                apellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                apellidoKeyTyped(evt);
            }
        });
        mes.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 280, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Fecha de nacimiento");
        mes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        dia.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dia.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diaActionPerformed(evt);
            }
        });
        mes.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Día:");
        mes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Mes:");
        mes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        Mes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre ", "Noviembre", "Diciembre" }));
        mes.add(Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("Año:");
        mes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        anio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        mes.add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("Correo electronico");
        mes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        Correo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Correo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CorreoActionPerformed(evt);
            }
        });
        Correo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                CorreoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                CorreoKeyTyped(evt);
            }
        });
        mes.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 280, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Contraseña");
        mes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        Contra.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Contra.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                ContraKeyPressed(evt);
            }
        });
        mes.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 280, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Sexo:");
        mes.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        masculino.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        masculino.setText("Masculino");
        masculino.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                masculinoActionPerformed(evt);
            }
        });
        mes.add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        femenino.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        femenino.setText("Femenino");
        mes.add(femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarActionPerformed
    {//GEN-HEADEREND:event_aceptarActionPerformed
        String emailIngresado = Correo.getText();
        String emailPattern = "^[a-zA-Z0-9._%+-]+@(gmail|hotmail|outlook|yahoo)\\.[a-zA-Z]{2,}$";

        Pattern emailPat = Pattern.compile(emailPattern);
        Matcher emailMatcher = emailPat.matcher(emailIngresado);

        int cve = pckBakcend.PrbClinicaDental.generarNumeroAleatorio();
        boolean isValidEmail = emailMatcher.matches();

        int dia = Integer.parseInt(this.dia.getSelectedItem().toString());
        String mes = Mes.getSelectedItem().toString();
        int anio = Integer.parseInt(this.anio.getSelectedItem().toString());
        String sexo = masculino.isSelected() ? "Masculino" : "Femenino";
        boolean sexoSeleccionado = masculino.isSelected() || femenino.isSelected();

        try
        {
            if (VtnIncio_Secion.usuario != null)
            {
                for (Usuario usuario : VtnIncio_Secion.usuario)
                {
                    if (usuario.getCorreo().equals(emailIngresado))
                    {
                        Mensaje.error(this, "Este correo ya está registrado. Por favor, use otro correo.");
                        return;
                    }
                }
            }

            if (isValidEmail)
            {
                if (!sexoSeleccionado)
                {
                    Mensaje.error(this, "Seleccione Un Sexo");
                    masculino.setSelected(false);
                    femenino.setSelected(false);
                } else
                {
                    if (masculino.isSelected() && femenino.isSelected())
                    {
                        Mensaje.error(this, "Seleccione Solo Un Sexo");
                        masculino.setSelected(false);
                        femenino.setSelected(false);
                    } else
                    {
                        Usuario obj = new Usuario(cve, nombre.getText(), apellido.getText(), dia, mes, anio, sexo, Correo.getText(), Contra.getText());
                        VtnIncio_Secion.usuario = insertaUsuario(obj, VtnIncio_Secion.usuario);
                        VtnIncio_Secion.consulta = crearMatrizConsulta(VtnIncio_Secion.consulta, VtnIncio_Secion.usuario);
                        VtnIncio_Secion.pagoRealizado = crearMatrizPagos(VtnIncio_Secion.pagoRealizado, VtnIncio_Secion.usuario);
                        VtnIncio_Secion.metodoPago = crearMatrizMetodoDePago(VtnIncio_Secion.metodoPago, VtnIncio_Secion.usuario);
                        Mensaje.exito(this, "Registro exitoso \n Su CVE es: " + cve);

                        archivos.Archivos.guardaArr(null, VtnIncio_Secion.usuario, "Datos.dat");
                        archivos.Archivos.guardaArr(null, VtnIncio_Secion.consulta, "DatosMatriz.dat");
                        archivos.Archivos.guardaArr(null, VtnIncio_Secion.pagoRealizado, "DatosPagos.dat");
                        archivos.Archivos.guardaArr(null, VtnIncio_Secion.metodoPago, "DatosMetodoDePago.dat");

                        dispose();
                        new VtnIncio_Secion().setVisible(true);
                        System.out.println(obj);
                    }
                }
            } else
            {
                Mensaje.error(this, "Correo Electrónico Inválido");
                CtrlInterfaz.limpia(Correo);
            }
        } catch (NullPointerException e)
        {
            Mensaje.error(this, "Error: La lista de usuarios no está inicializada.");
        } catch (Exception e)
        {
            Mensaje.error(this, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diaActionPerformed
    {//GEN-HEADEREND:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreKeyPressed
    {//GEN-HEADEREND:event_nombreKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, nombre, apellido);
    }//GEN-LAST:event_nombreKeyPressed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombreKeyTyped
    {//GEN-HEADEREND:event_nombreKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_nombreKeyTyped

    private void apellidoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoKeyPressed
    {//GEN-HEADEREND:event_apellidoKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, apellido, Correo);
    }//GEN-LAST:event_apellidoKeyPressed

    private void apellidoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_apellidoKeyTyped
    {//GEN-HEADEREND:event_apellidoKeyTyped
        Validaciones.validaAlfabeticos(evt);
    }//GEN-LAST:event_apellidoKeyTyped

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CorreoActionPerformed
    {//GEN-HEADEREND:event_CorreoActionPerformed

    }//GEN-LAST:event_CorreoActionPerformed

    private void ContraKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_ContraKeyPressed
    {//GEN-HEADEREND:event_ContraKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, Contra, aceptar);
    }//GEN-LAST:event_ContraKeyPressed

    private void CorreoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CorreoKeyTyped
    {//GEN-HEADEREND:event_CorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoKeyTyped

    private void CorreoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_CorreoKeyPressed
    {//GEN-HEADEREND:event_CorreoKeyPressed
        Validaciones.enterCadenaNoVacia(this, evt, Correo, Contra);
    }//GEN-LAST:event_CorreoKeyPressed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_masculinoActionPerformed
    {//GEN-HEADEREND:event_masculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masculinoActionPerformed

    public static Object[] cargarArreglo(String nombreArchivo)
    {
        try
        {
            FileInputStream fis = new FileInputStream("ArchivosClinicaDental/" + nombreArchivo);

            ObjectInputStream ois = new ObjectInputStream(fis);
            Object[] arr = (Object[]) ois.readObject();
            ois.close();
            return arr;
        } catch (FileNotFoundException e)
        {
            System.out.println("Archivo no encontrado: " + nombreArchivo);
            return null;
        } catch (Exception e)
        {
            System.out.println("Error al leer el archivo: " + e);
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VtnRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contra;
    private javax.swing.JTextField Correo;
    private javax.swing.JComboBox<String> Mes;
    private javax.swing.JToggleButton aceptar;
    private javax.swing.JComboBox<String> anio;
    private javax.swing.JTextField apellido;
    private javax.swing.JComboBox<String> dia;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JPanel mes;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
